### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [ymegane/approom#3]
It would be handy to have this app distributed through F-Droid. Do you think that would be feasible?

**Comment by ymegane** [comment]
@pizzamaker 
Thanks your opinion !😄 
Sorry, I didn't know F-Droid. So I was a little googled..

Basically I'm not going to be distributed outside of GooglePlay.
Because this app is an app to share the URL of GooglePlay 🛍 

I thought it was too much meaning is not.
If I distributed on F-Droid, do you think that the user come in handy?
